### ISSUE TITLE
Update the CLI tool to support the latest OSCAL models

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/oscal-tools#3]
# User Story:

As an OSCAL content user, I need a simple tool that can perform common actions on OSCAL content. These actions include:

- Validating an OSCAL content instance against the appropriate schema/schematron
- Performing Profile resolution of an OSCAL Profile
- Producing renderings of OSCAL content (e.g., Catalog, Profile, SSP) in human-readable formats (e.g., HTM, PDF)

The [CLI tool](cli) has not been updated to the latest OSCAL catalog, profile, component, and SSP models. 

## Goals:

Update the CLI tool to support:
- [ ] Validating an OSCAL content instance
- [ ] Converting an OSCAL content instance between XML, JSON, and YAML formats.
- [ ] Renders an OSCAL content instance into human-readable formats

## Dependencies

#575 will provide the rendering capabilities needed by the tool.

**Comment by wendellpiez** [comment]
@david-waltermire-nist I am marking this as closable since the CLI tool now has its own repo?

https://github.com/usnistgov/oscal-cli - noting there are no Issues there yet.

Potential spin-off Issue: writeup of `oscal-cli` tools in the OSCAL Tools site (this repo).
