### ISSUE TITLE
Migrate and update XSLTs for publishing

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/oscal-tools#4]
There is OSCAL WIP here, on publishing XSLTs: https://github.com/wendellpiez/OSCAL/tree/publishing-v0dot1

Additionally, there are (at least) two Issues in the OSCAL repo tracking this work: usnistgov/oscal#574 and usnistgov/oscal#630.

This work needs to be completed (to a stable point) and documented.

## Acceptance Criteria

- [x] XSLTs for catalogs and resolved profiles work effectively on SP800-53 examples, both rev 4 and rev 5, producing HTML and PDF, in freely distributable tools (SaxonHE and FOP)
- [x] XSLTs for other document types (e.g., SSP) reflect best-reasonable efforts given available samples or demo docs
- [x] User docs explain how to use the XSLTs, for example using Saxon from a command line
- [x] A PR into this repo includes this work

NB: to produce PDFs, Saxon alone is not enough: users also need Apache FOP or another XSL-FO formatting engine. While we may not wish to distribute these packages, we may wish to provide some level of support, for example via maven.

**Comment by wendellpiez** [comment]
@david-waltermire-nist this Issue in the oscal-tools repo, should we close it?

Same work item as usnistgov/oscal#630

**Comment by david-waltermire** [comment]
We can close this when usnistgov/oscal-xslt#9 is done.

**Comment by wendellpiez** [comment]
See also work being done in the FedRAMP automation repository on SSP rendering: https://github.com/GSA/fedramp-automation

**Comment by wendellpiez** [comment]
Suggest we spin off a new Issue for SSP preview mentioned here, and close this Issue.

**Comment by wendellpiez** [comment]
An SSP Preview XSLT is now described on usnistgov/OSCAL#43.
