### ISSUE TITLE
Add "closable" label to this repository

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/oscal-tools#41]
To support expediting workflow in Issues maintenance, this Github repo needs a "closable" label or functional equivalent.

It can be whatever color is deemed appropriate.

Optional add-on: add 'closable' to the Labels configuration upstream.

**Comment by david-waltermire-nist** [comment]
I added a [GitHub action](https://github.com/usnistgov/oscal-tools/blob/main/.github/workflows/labels.yml) and a [config file](https://github.com/usnistgov/oscal-tools/blob/main/.github/labels.json) that will be used to configure labels. You can now submit a PR against the config file to add new labels.
