### ISSUE TITLE
Update README and Archive Project

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/oscal-tools#77]
- [ ] Create a PR and add this section to the top of the README, using [the wording I am providing in this HackMD](https://hackmd.io/BDUgAm96QC6CrP_wQSuqig), get it reviewed, and merged as quickly as possible.
- [ ] Add a banner to the application landing page. If you do not use the USWDS, you should still mimic the style of the example as seen in the example below. You are imitating the blue box in this screenshot. Replace "This website is in the alpha stage of development. Help us improve ->" with the following text for this project's website: "This website and its code are no longer under active development, read more details [here](https://github.com/usnistgov/oscal-tools#project-status)." You do not want to include help us improve: the link to the README page with the updated project status will suffice. Instead of the bright blue color, please set the background to `#d9e8f6`.

![Image](https://user-images.githubusercontent.com/94922603/225163904-2dea5a27-1868-4e19-a75a-38a34db1c51d.png)

- [ ] Confirm usnistgov/OSCAL#118 is complete (see dependencies below)
- [ ] Archive the project [using the instructions from GitHub](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#archiving-a-repository). If you do not have sufficient permissions, please reach out to @aj-stein-nist to get this done.

Dependencies:

- [ ] Completion of all XSLT for OSCAL pipeline support moved to oscal-xslt.
- [ ] Completion of https://github.com/usnistgov/oscal-cat/issues/118 so notice of similar pause of OSCAL CAT is present in last push of this site to pages.nist.gov

**Comment by aj-stein-nist** [comment]
@wendellpiez as discussed today when pairing on related issues, can you please work on this during the sprint with the intent to resolve it by 15 March 2023? If you have concerns about finishing it by then, or think you need help to do so to finish it by then, please let me know. It will be superful help, thanks!

**Comment by wendellpiez** [comment]
Started on this by copying all the WIP sitting in my fork out to a branch of the `oscal-xslt` repo to be merged there.

Next steps here (in a branch):

- [ ] remove `xslt` and other unwanted folders
- [ ] rewrite top-level readme
- [ ] rewrite site under `docs` directory w/ Hugo precheck

**Comment by nikitawootten-nist** [comment]
Update: the team plans to draft a unified archiving message before making individual PRs.

**Comment by aj-stein-nist** [comment]
@wendellpiez I updated the checklist for completion of this task to address some questions and ambiguities around the work it is in the updated issue description above. I hope this clarifies what needs to be done. Please let me know if you cannot complete by COB tomorrow (end of sprint).

**Comment by wendellpiez** [comment]
@aj-stein-nist I can work on this but it's going to be a close one.

Main reason being that adding a banner in Hugo with language and styling has to be done through templating. Is anyone else having to set this up in Hugo?

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist I can work on this but it's going to be a close one.
> 
> Main reason being that adding a banner in Hugo with language and styling has to be done through templating. Is anyone else having to set this up in Hugo?

We can work together on this but it seems beyond the USA banner there is a DRAFT equivalent we can work off of:

https://github.com/usnistgov/hugo-uswds/blob/2d6444fcb9f788e275dcc56cbee2ef7002045e2c/layouts/partials/components/draft-banner.html

Similar idea, different content, is this a good starting point?

**Comment by wendellpiez** [comment]
I actually designed and deployed a 'draft' banner -- problem there being it requires a flag on each page as you say.

Instead I am hacking a `usa-banner` into the banner.html template, which seems to work so far.

![image](https://user-images.githubusercontent.com/1588228/225327123-7f6cee27-1bb3-49a4-a296-741698b30bc6.png)

**Comment by wendellpiez** [comment]
![image](https://user-images.githubusercontent.com/1588228/225332131-3068fe51-1143-43fd-ab48-baa820c26889.png)

I changed the language slightly to say a tiny bit less.
